title: <p align="center"> Hardik Gupta </p>

#logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/hardiklgupta/">LinkedIn</a> |
  <a href="https://github.com/HardikLGupta">GitHub</a> |
  <a href="https://stackoverflow.com/users/3811401/hardik-gupta">StackOverflow</a>
  </p>
  
  <p align="justify">
  Senior Data Scientist with 8+ yrs. of experience including Data Science, Machine Learning and Deep Learning, across Gaming, Media/Entertainment, Logistics and Software domain.
  </p>

  <p style="font-weight:bold"> Education </p>
  <ul>
  <li>Gold Medal recipient in Advance Management Program in Business Analytics from ISB</li>
  <li>Data Driven Modelling and Optimisation from IISc Bangalore</li>
  <li>Artificial intelligence with DL Certification from One Fourth Labs (IIT Madras research Park incubated start-up founded Professors at IIT Madras)</li>
  </ul>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
