title: <p align="center"> Hardik Gupta </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/hardiklgupta/">LinkedIn</a> |
  <a href="https://github.com/HardikLGupta">GitHub</a> |
  <a href="https://stackoverflow.com/users/3811401/hardik-gupta">StackOverflow</a>
  </p>
  
  <p align="justify">
  Research driven with strong belief in bringing together intuition for product insights, data visualisation, art of feature engineering, mathematical modelling, 
  scalable engineering and online experiments in collaborative environments. 
  8+ yrs. of experience including Data Science, Machine Learning and Deep Learning, across Gaming, Media/Entertainment, Logistics and Software domain. 
  Strong expertise in translating business problem into data problem. 
  4200+ points on stack overflow
  </p>
  <br><br>

  <p font-weight="bold"> 
  Education
  - Gold Medal recipient in Advance Management Program in Business Analytics from Indian School of Business
  - Data Driven Modelling and Optimisation from Indian Institute of Science Bangalore (Grade A+)
  - Artificial intelligence with Deep Learning Certification from One Fourth Labs (IIT Madras research Park incubated start-up founded Professors at IIT Madras)
  </p>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
